field: 7f511051-af46-43d3-9ffa-a0259bbd18fa # Blocks
fieldLayouts:
  ce55d5dd-b205-4fbd-81ee-ddad531aef79:
    tabs:
      -
        elements:
          -
            fieldUid: a3cc9794-e75d-4518-a9b8-5d8f50e49c6b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3aac75d-99b0-49ce-ae1b-923b013999da
            warning: null
            width: 100
        name: Content
        uid: 53cd166f-aafc-411e-af32-6e9cf19b67a8
fields:
  a3cc9794-e75d-4518-a9b8-5d8f50e49c6b: # Heading
    columnSuffix: hlqlxhjj
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: componentOne
name: 'Component One'
sortOrder: 1
