field: 7f511051-af46-43d3-9ffa-a0259bbd18fa # Blocks
fieldLayouts:
  c1237995-a341-4b21-bb84-4737529a65ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 68f49541-781b-46d3-8b29-c868d5f18eae
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9893cff-de9d-4a91-8532-4d554d2b8513
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3604c7ea-ffe5-43ae-a962-f0af9e6cc2e1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05ee9c1f-ae0e-41f0-9c76-613889f0a8ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b35e421d-7d80-4773-a2fe-b0ec6f77a6d0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae2e7bd2-f257-4978-9331-3b45c9b636b1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e52117cc-943e-441b-9a33-66af248624ac
        userCondition: null
fields:
  68f49541-781b-46d3-8b29-c868d5f18eae:
    columnSuffix: yhkyrrrf
    contentColumnType: text
    fieldGroup: null
    handle: faqHeading
    instructions: null
    name: 'Faq Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3604c7ea-ffe5-43ae-a962-f0af9e6cc2e1:
    columnSuffix: zgxmvjvo
    contentColumnType: text
    fieldGroup: null
    handle: faqLeadtext
    instructions: null
    name: 'Faq Leadtext'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b35e421d-7d80-4773-a2fe-b0ec6f77a6d0:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: faqs
    instructions: null
    name: Faqs
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 928948559
      contentTable: '{{%stc_faqs}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: faq
name: Faq
sortOrder: 5
