field: 7f511051-af46-43d3-9ffa-a0259bbd18fa # Blocks
fieldLayouts:
  5d340bdc-e021-4b46-9b4a-3e5bffb84e03:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7c6328bf-ece2-4e54-97b1-4ac2218c9a3d # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fb669e9-fdd3-416f-b3ec-432f8197556e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e437fca-1e82-45c8-93e0-9f1605ee6be6
        userCondition: null
fields:
  7c6328bf-ece2-4e54-97b1-4ac2218c9a3d: # Headline
    columnSuffix: bbntacfx
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: header
name: Header
sortOrder: 2
