fieldLayouts:
  93fb2be0-e7b9-4a08-a0a5-6e11a0e3c9fa:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae8aca0a-9bee-4b1b-9a0c-8dd19f0b3bb2
            warning: null
            width: 100
          -
            fieldUid: 5ff08539-481e-4862-8dec-aa786e6170c0 # Home Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b5f947b-cf98-4831-a564-81a73266ae56
            warning: null
            width: 100
          -
            fieldUid: 7f511051-af46-43d3-9ffa-a0259bbd18fa # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67ee4e29-63f9-4a18-83f0-c70d4e72f911
            warning: null
            width: 100
        name: Content
        uid: 2f6900ca-8d71-4719-be6b-c15d3fa5a10d
handle: homepage
hasTitleField: true
name: Homepage
section: c6069214-1223-40bc-8630-f90df546e67a # Homepage
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
