fieldLayouts:
  1bc43f46-b519-4d77-b02f-9d572b2f0f3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3685eebf-5cf1-4539-8289-31aaae019eb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da903d5e-291f-4a50-bce9-f95305d654f0 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2b8303e-7956-4380-aeb8-9d3e13e3f70d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a3035bf-54fb-4b3d-a50c-aa0b469ed0d0 # Article Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65483af0-a1c7-45b9-8623-72b4d95066d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 664838f9-adf5-4726-ba01-55096819a0d7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ff08539-481e-4862-8dec-aa786e6170c0 # Home Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb6bd68d-28a8-41cd-9502-7f1d70565ad0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 306181c3-0ac1-466b-9ad1-02aca87eb389 # Project Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c020991f-595e-498b-8ce3-204dae6f72c2
            userCondition: null
            warning: null
            width: 100
        name: SEO/Meta
        uid: 6a4f7bbf-f303-4280-91e2-b19122d87c82
        userCondition: null
handle: recipes
hasTitleField: true
name: Recipes
section: d111679a-1277-4b40-8262-d777755e94b5 # Recipes
sortOrder: 1
titleFormat: '{entry.title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
