columnSuffix: null
contentColumnType: string
fieldGroup: 8e5b45c8-ee87-45ca-9bb0-d487dc8d6d89 # Common
handle: pageBlocks
instructions: null
name: Blocks
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
