field: b35e421d-7d80-4773-a2fe-b0ec6f77a6d0 # Faqs
fieldLayouts:
  1daabafe-0410-43ab-a7da-87f365fa3a8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9650dc52-e44c-4eaa-b2b3-43586f2d8e7d # Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e17b01-bc6f-46c2-8b79-72da1ebafae4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55194761-393e-4eae-b760-045a3d1ad44d # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3d91c0-84f1-491b-aece-11c113196b8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5008b70-c18f-4a83-8ee7-0c8fe68d6652
        userCondition: null
fields:
  9650dc52-e44c-4eaa-b2b3-43586f2d8e7d: # Question
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: null
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  55194761-393e-4eae-b760-045a3d1ad44d: # Answer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
