field: b35e421d-7d80-4773-a2fe-b0ec6f77a6d0
fieldLayouts:
  1daabafe-0410-43ab-a7da-87f365fa3a8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9650dc52-e44c-4eaa-b2b3-43586f2d8e7d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeb186e9-2c85-4dcf-9139-1f8c7077db49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55194761-393e-4eae-b760-045a3d1ad44d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac5fe641-4bdb-4b7e-a61d-049744866c71
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5008b70-c18f-4a83-8ee7-0c8fe68d6652
        userCondition: null
fields:
  9650dc52-e44c-4eaa-b2b3-43586f2d8e7d:
    columnSuffix: symkllnl
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: null
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  55194761-393e-4eae-b760-045a3d1ad44d:
    columnSuffix: fvtayyoj
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
