defaultPlacement: end
enableVersioning: true
handle: articles
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bb85afe2-0660-40bb-ad67-bfe6b9f6dda0: # Servd Test
    enabledByDefault: true
    hasUrls: true
    template: articles/_entry
    uriFormat: 'articles/{slug}'
type: channel
