defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - 'https://pixnext-rooleary.vercel.app/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug={slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Local
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug={slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bb85afe2-0660-40bb-ad67-bfe6b9f6dda0: # Servd Test
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'pages/{slug}'
structure:
  maxLevels: null
  uid: 9427f514-cbad-4290-a470-728ec43ff1ac
type: structure
