defaultPlacement: end
enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bb85afe2-0660-40bb-ad67-bfe6b9f6dda0: # Servd Test
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'projects/{slug}'
structure:
  maxLevels: null
  uid: 62540f03-f9f7-404d-878f-65260e9e80db
type: structure
