defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - 'https://pixnext-rooleary.vercel.app/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug=recipes/{slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Local
      -
        - urlFormat
        - 'http://localhost:3000/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug=recipes/{slug}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - AWS
      -
        - urlFormat
        - 'https://production.dioy5gcvj0xuv.amplifyapp.com/api/preview?token=WxQXrQAuWGI1LvhIKpXjSGESi8ff8NcjjmMNiQZVB7H6pml6uRVNcoCL0ZQEcwQv&canonicalId&slug=recipes/{slug}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  102a2f0f-e972-40b4-ae51-c15fb2cdaf03: # Servd Test NL
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  bb85afe2-0660-40bb-ad67-bfe6b9f6dda0: # Servd Test
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'recipes/{slug}'
type: channel
